from dataclasses import dataclass


@dataclass(frozen=True)
class AlarmInfo:
    friendly_name: str
    trigger: str
    possible_cause: str
    product_action: str
    service_action: str


ALARM_CODES: dict[int, AlarmInfo] = {
    1: AlarmInfo(
        "Outdoor Sensor Error (BT1)",
        "Outdoor temperature sensor BT1 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset required.",
        "Check connections; replace sensor if needed.",
    ),
    2: AlarmInfo(
        "Indoor Sensor Error (BT2)",
        "Indoor temperature sensor BT2 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; block indoor curve compensation.",
        "Check connections; replace sensor if needed.",
    ),
    3: AlarmInfo(
        "Pool Sensor Error (BT4)",
        "Pool temperature sensor BT4 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset required.",
        "Check connections; replace sensor if needed.",
    ),
    4: AlarmInfo(
        "Flow Line Sensor Error (BT11)",
        "Supply temperature sensor BT11 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; switch to manual mode; block distribution system heating.",
        "Check connections; replace sensor if needed.",
    ),
    5: AlarmInfo(
        "External Flow Line Sensor Error (BT12)",
        "External supply temperature sensor BT12 is outside the allowed range.",
        "Sensor missing, failure, or bad connection.",
        "Manual reset required.",
        "Check connections; replace sensor if needed.",
    ),
    6: AlarmInfo(
        "Tank Temperature Sensor Error (BT30)",
        "DHW tank temperature sensor BT30 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; block DHW pump GP2, DHW production, and mixing valve QN8; switch to manual mode.",
        "Check connections; replace sensor if needed.",
    ),
    7: AlarmInfo(
        "Heating Medium PHEX Inlet Sensor Error (BT31)",
        "Heating medium PHEX inlet sensor BT31 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; block DHW pump GP2.",
        "Check connections; replace sensor if needed.",
    ),
    9: AlarmInfo(
        "Hot Water PHEX Outlet Sensor Error (BT34)",
        "Hot water PHEX outlet sensor BT34 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block DHW pump GP2.",
        "Check connections; replace sensor if needed.",
    ),
    10: AlarmInfo(
        "Auxiliary Input Error (BTX)",
        "Invalid input on auxiliary input BTX.",
        "Auxiliary input fault or bad connection.",
        "Auto-reset; block pool heating.",
        "Check input signal; replace sensor if needed.",
    ),
    11: AlarmInfo(
        "Condenser Outlet Sensor Error (BT10)",
        "Condenser outlet sensor BT10 is outside the allowed range.",
        "Sensor missing, failure, or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    13: AlarmInfo(
        "Source Flow Sensor Error (BT14)",
        "Source inlet sensor BT14 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    14: AlarmInfo(
        "Source Return Flow Sensor Error (BT15)",
        "Source outlet sensor BT15 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    15: AlarmInfo(
        "Sink Flow Sensor Error (BT20)",
        "Discharge line sensor BT20 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    19: AlarmInfo(
        "Suction Line Sensor Error (BT23)",
        "Suction line sensor BT23 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    21: AlarmInfo(
        "Low Pressure Transmitter Error (BP1)",
        "Low-pressure transmitter BP1 is outside the allowed range.",
        "Transmitter failure or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    22: AlarmInfo(
        "High Pressure Transmitter Error (BP2)",
        "High-pressure transmitter BP2 is outside the allowed range.",
        "Transmitter failure or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    27: AlarmInfo(
        "Com EA2W Module Error",
        "Communication with compressor module was lost.",
        "Software issue, failed update, or faulty wiring.",
        "Manual reset; block compressor, force immersion heater, and block DHW pump GP2.",
        "Check cable and connections between main board and fan control board.",
    ),
    29: AlarmInfo(
        "Inverter Error 5x in 3 hours",
        "Inverter fault occurred five times within three hours.",
        "Insufficient flow or inverter wiring fault.",
        "Manual reset; block compressor; force immersion heater.",
        "Check flow and power supply.",
    ),
    30: AlarmInfo(
        "Filter Change Alarm",
        "Filter change interval elapsed.",
        "Exhaust air filters are dirty or worn out.",
        "Manual reset required.",
        "Replace filters.",
    ),
    31: AlarmInfo(
        "Hot Gas Alarm",
        "Discharge temperature envelope exceeded.",
        "Compressor malfunction or refrigerant leakage.",
        "Manual reset; block compressor; force immersion heater.",
        "Replace compressor unit.",
    ),
    33: AlarmInfo(
        "High Pressure Alarm",
        "Pressure envelope exceeded (high-pressure transmitter, BP2).",
        "Insufficient flow.",
        "Manual reset required; block compressor; force immersion heater.",
        "Check circulation pump; ensure sufficient flow in heating system.",
    ),
    35: AlarmInfo(
        "Low Pressure Alarm",
        "Pressure envelope exceeded (low-pressure transmitter, BP1).",
        "Refrigerant leakage or insufficient exhaust-air flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Check fan and filters; replace compressor unit.",
    ),
    37: AlarmInfo(
        "Source Temperature Alarm",
        "Compressor repeatedly stopped because source temperature BT15 was low.",
        "Source temperature too low or insufficient source-medium flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Close outdoor-air damper and increase fan speed.",
    ),
    39: AlarmInfo(
        "EEV Actuator Malfunction",
        "Superheat repeatedly outside range for EEV QN1.",
        "Refrigerant leakage, EEV fault, or faulty BT23 sensor.",
        "Manual reset; block compressor; force immersion heater.",
        "Check leakage; replace EEV actuator or BT23 sensor.",
    ),
    42: AlarmInfo(
        "BT23 Low Temperature Alarm",
        "Suction line temperature BT23 is low.",
        "Refrigerant leakage, EEV fault, or faulty BT23 sensor.",
        "Manual reset; block compressor; force immersion heater.",
        "Check leakage; replace EEV actuator or BT23 sensor.",
    ),
    43: AlarmInfo(
        "No Communication With Outdoor Module",
        "Communication with heat pump was lost.",
        "No power, faulty communication, or start-up sequence error.",
        "Manual reset; block compressor; force immersion heater.",
        "Check communication cable and connections.",
    ),
    44: AlarmInfo(
        "Low Defrost Flow",
        "Defrost attempt repeatedly failed.",
        "Insufficient condenser flow or faulty flow switch.",
        "Manual reset; block compressor; force immersion heater.",
        "Check circulation pump, flow switch, and heating-system flow.",
    ),
    45: AlarmInfo(
        "Fan Error (No RPM Feedback)",
        "Fan speed signal repeatedly faulted.",
        "Fan hardware fault or faulty fan/control-board wiring.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check fan wiring and fan-board connection.",
    ),
    47: AlarmInfo(
        "Incompatible Software in the Outdoor Module",
        "Obsolete or incompatible outdoor-module software detected.",
        "Heat-pump software is incompatible with controller.",
        "Manual reset; block compressor; force immersion heater.",
        "Update heat-pump software.",
    ),
    53: AlarmInfo(
        "Cooling blocked - Low ambient temperature",
        "Cooling requested at too-low outdoor temperature.",
        "Cooling request at low outdoor-air temperature.",
        "Auto-reset.",
        "None.",
    ),
    60: AlarmInfo(
        "Anti-freeze protection",
        "Anti-freeze protection triggered.",
        "Low system-circuit temperature.",
        "Manual reset; block compressor; force immersion heater.",
        "Force immersion heater until temperature increases.",
    ),
    61: AlarmInfo(
        "Low water flow protection",
        "Low water flow protection triggered.",
        "Insufficient distribution-system flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; increase pump speed; open thermostats.",
    ),
    64: AlarmInfo(
        "Exhaust temperature overprotection",
        "Exhaust temperature BT20 is high.",
        "Compressor malfunction or refrigerant leakage.",
        "Manual reset; block compressor; force immersion heater.",
        "Check refrigerant leakage and compressor function.",
    ),
    69: AlarmInfo(
        "High flow temperature difference protection",
        "Delta-T across condenser is high.",
        "Insufficient condenser flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; increase pump speed; open thermostats.",
    ),
    70: AlarmInfo(
        "Outlet water over heat",
        "Outlet water temperature BT10 is high.",
        "Insufficient condenser flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; increase pump speed; open thermostats.",
    ),
    84: AlarmInfo(
        "High pressure protection 3 times",
        "Pressure exceeded maximum limit three times in thirty minutes.",
        "Insufficient condenser flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; increase pump speed; open thermostats.",
    ),
    86: AlarmInfo(
        "Low pressure protection 3 times",
        "Pressure fell below minimum limit three times in thirty minutes.",
        "Faulty defrosting or refrigerant leakage.",
        "Manual reset; block compressor; force immersion heater.",
        "Check refrigerant leakage and compressor function.",
    ),
    90: AlarmInfo(
        "Low water flow protection 3+",
        "Low water flow occurred three times in one hour.",
        "Insufficient distribution-system flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; increase pump speed; open thermostats.",
    ),
    92: AlarmInfo(
        "Anti-freeze protection 3 times",
        "Anti-freeze protection occurred three times.",
        "Low system-circuit temperature.",
        "Manual reset; block compressor; force immersion heater.",
        "Force immersion heater until temperature increases.",
    ),
    96: AlarmInfo(
        "Discharge over heat protection 3 times",
        "High BT20 exhaust temperature occurred three times in thirty minutes.",
        "Compressor malfunction or refrigerant leakage.",
        "Manual reset; block compressor; force immersion heater.",
        "Check refrigerant leakage and compressor function.",
    ),
    98: AlarmInfo(
        "High flow temperature difference protection 3 times",
        "High condenser delta-T occurred three times in thirty minutes.",
        "Insufficient water flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; increase pump speed; open thermostats.",
    ),
    99: AlarmInfo(
        "Low outlet water temp 3 times",
        "Low BT10 outlet temperature occurred three times in thirty minutes.",
        "Insufficient flow, incorrect configuration, or closed thermostats.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; check circulation pump; open thermostats.",
    ),
    100: AlarmInfo(
        "Outlet water overtemperature protection 3 times",
        "High BT10 outlet temperature occurred three times in thirty minutes.",
        "Insufficient condenser flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Clean filters; increase pump speed; open thermostats.",
    ),
    112: AlarmInfo(
        "Inlet water temperature failure",
        "Heating return sensor BT13 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater; use DHW control without BT13.",
        "Check connections; replace sensor if needed.",
    ),
    113: AlarmInfo(
        "Outlet water temperature failure",
        "Outlet water sensor BT10 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    114: AlarmInfo(
        "Coil temperature failure",
        "Evaporator outlet sensor BT25 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset.",
        "Check connections; replace sensor if needed.",
    ),
    115: AlarmInfo(
        "Ambient temperature failure",
        "Ambient sensor BT14 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset.",
        "Check connections; replace sensor if needed.",
    ),
    116: AlarmInfo(
        "Suction temperature failure",
        "Suction line sensor BT23 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset.",
        "Check connections; replace sensor if needed.",
    ),
    123: AlarmInfo(
        "Discharge temperature failure",
        "Exhaust sensor BT20 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    126: AlarmInfo(
        "Low ambient temperature failure",
        "Ambient temperature is low.",
        "Ambient temperature too low or excessive sensor deviation.",
        "Auto-reset; block compressor; force immersion heater.",
        "Protect heat pump and pipework from freezing.",
    ),
    127: AlarmInfo(
        "Low outlet water temperature",
        "Outlet water temperature BT10 is low.",
        "Insufficient flow, incorrect configuration, or closed thermostats.",
        "Auto-reset; block compressor; force immersion heater.",
        "Clean filters; check circulation pump; open thermostats.",
    ),
    139: AlarmInfo(
        "Fan 1 failure",
        "Fan 1 failed on heat pump.",
        "Bad parameters, connection, communication, or fan module.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check fan wiring and connections; replace fan.",
    ),
    140: AlarmInfo(
        "Fan 2 failure",
        "Secondary fan failed.",
        "Communication failure between main board and fan module.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check fan wiring and connections; replace fan.",
    ),
    141: AlarmInfo(
        "Communication failure (mainboard with fan motor module board)",
        "Communication between main board and fan module is faulty.",
        "Poor contact or damaged communication wiring/port.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check fan wiring and connections; replace fan control board if needed.",
    ),
    143: AlarmInfo(
        "Communication failure (mainboard with fan motor 2 module board)",
        "Communication with secondary fan module is faulty.",
        "Poor contact or damaged communication wiring/port.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check fan wiring and connections.",
    ),
    144: AlarmInfo(
        "IPM overheat",
        "Inverter temperature is high.",
        "Fan not rotating with high current or insufficient thermal coupling.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check fan function.",
    ),
    145: AlarmInfo(
        "Compressor start failure",
        "Compressor drive failed.",
        "Incorrect model code, faulty wiring, or damaged inverter board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check compressor wiring; replace inverter board.",
    ),
    146: AlarmInfo(
        "Compressor over current",
        "Compressor current is too high.",
        "Damaged current-detection circuit.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure compressor current.",
    ),
    147: AlarmInfo(
        "Input voltage phase loss",
        "Input voltage phase loss detected.",
        "Incorrect power connection, damaged fuse, or inverter drive.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check incoming power supply.",
    ),
    148: AlarmInfo(
        "IPM current sampling fault",
        "AC current measurement is incorrect.",
        "Phase imbalance or damaged inverter board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check power supply; replace inverter.",
    ),
    149: AlarmInfo(
        "Overheat protection of drive board devices",
        "Drive-board device overheat protection triggered.",
        "Fan not running or poor thermal coupling.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check fan function.",
    ),
    150: AlarmInfo(
        "Pre-charge failure",
        "Pre-charge failed.",
        "Input phase loss or power cycling before full discharge.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    151: AlarmInfo(
        "DC bus overvoltage",
        "DC bus voltage is above permitted limit.",
        "Input voltage too high or damaged sampling circuit.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    152: AlarmInfo(
        "DC bus undervoltage",
        "DC bus voltage is below permitted limit.",
        "Input voltage too low or damaged sampling circuit.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    153: AlarmInfo(
        "AC input voltage undervoltage",
        "Input voltage is too low.",
        "Grid voltage below operating range.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    154: AlarmInfo(
        "AC input overcurrent shutdown",
        "Input current is high.",
        "Damaged current-sampling circuit.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    155: AlarmInfo(
        "Input voltage sampling fault",
        "Incoming supply is outside expected range.",
        "Abnormal input voltage or damaged sampling circuit.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    156: AlarmInfo(
        "DSP and PFC communication failure",
        "Communication between DSP and PFC is faulty.",
        "Damaged driver board or control electronics.",
        "Auto-reset; block compressor; force immersion heater.",
        "Replace driver board.",
    ),
    157: AlarmInfo(
        "Drive plate temperature fault",
        "Drive-board temperature is outside the allowed range.",
        "Damaged sensor or inverter board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Replace inverter board.",
    ),
    158: AlarmInfo(
        "DSP and communication board communication failure",
        "Communication between DSP and communication board is faulty.",
        "Damaged driver board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Replace driver board.",
    ),
    159: AlarmInfo(
        "Mainboard communication failure",
        "Mainboard communication failure detected.",
        "Damaged wiring or controller board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check wiring; replace controller board.",
    ),
    161: AlarmInfo(
        "Compressor default phase",
        "Compressor has a phase loss.",
        "Incorrect wiring or damaged compressor.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    163: AlarmInfo(
        "Faulty input current sampling",
        "Input current measurement is incorrect.",
        "Damaged switched-mode power supply or inverter board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure supply; replace inverter board.",
    ),
    166: AlarmInfo(
        "EEPROM fault",
        "EEPROM data is invalid.",
        "Corrupted EEPROM data or damaged inverter board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Replace inverter board.",
    ),
    167: AlarmInfo(
        "Input voltage overlimiting protection",
        "AC input voltage exceeds maximum limit.",
        "Grid overvoltage or damaged sampling circuit.",
        "Auto-reset; block compressor; force immersion heater.",
        "Measure incoming power supply.",
    ),
    175: AlarmInfo(
        "Compressor overspeed protection",
        "Compressor speed is too high.",
        "Incorrect model code or damaged inverter board.",
        "Auto-reset; block compressor; force immersion heater.",
        "Replace inverter board.",
    ),
    247: AlarmInfo(
        "Return water temperature sensor fault",
        "Condenser inlet sensor BT13 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    248: AlarmInfo(
        "Outlet water temperature sensor fault",
        "Condenser outlet sensor BT10 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    253: AlarmInfo(
        "Fault of water inlet sensor at water source side",
        "Source inlet sensor BT14 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    254: AlarmInfo(
        "Fault of water outlet temperature sensor at water source side",
        "Source outlet sensor BT15 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    256: AlarmInfo(
        "Exhaust temperature sensor fault",
        "Discharge line sensor BT20 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    257: AlarmInfo(
        "Suction air temperature sensor fault",
        "Suction line sensor BT23 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check connections; replace sensor if needed.",
    ),
    269: AlarmInfo(
        "Main Control-Press Driver Communication Failure",
        "Communication between inverter driver and controller chip was lost.",
        "Missing software, damaged driver chip, or damaged hardware circuit.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    274: AlarmInfo(
        "Driver DC bus overvoltage and undervoltage protection",
        "DC bus voltage is outside compressor voltage envelope.",
        "Internal inverter hardware fault.",
        "Auto-reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    275: AlarmInfo(
        "Low pressure sensor failure",
        "Low-pressure sensor BP1 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Replace compressor unit.",
    ),
    276: AlarmInfo(
        "High pressure sensor fault",
        "High-pressure sensor BP2 is outside the allowed range.",
        "Sensor failure or bad connection.",
        "Auto-reset; block compressor; force immersion heater.",
        "Replace compressor unit.",
    ),
    279: AlarmInfo(
        "Fault of water flow switch on the ground source side",
        "Low flow at GP4 pump or BF2 flow sensor.",
        "Insufficient source-medium flow.",
        "Auto-reset.",
        "Check source-medium flow.",
    ),
    306: AlarmInfo(
        "Driver module protection (FO)",
        "Driver protection triggered three times within one hour.",
        "Compressor malfunction, internal inverter fault, or faulty wiring.",
        "Manual reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    307: AlarmInfo(
        "Compressor out of step/or start failure/phase loss",
        "Compressor start failure occurred three times within one hour.",
        "Compressor out of step or phase loss despite restarts.",
        "Manual reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    308: AlarmInfo(
        "Driver input overcurrent protection/phase current overcurrent protection/current detection circuit fault",
        "High input current occurred three times within one hour.",
        "Current exceeds maximum despite restart attempts.",
        "Manual reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    309: AlarmInfo(
        "Driver module hardware protection/IPM module temperature sensor fault",
        "Inverter temperature signal unavailable three times within one hour.",
        "IPM sensor failure or bad connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    310: AlarmInfo(
        "Low pressure switch off protection (Low low pressure protection)",
        "Low BP1 pressure occurred three times within one hour.",
        "Insufficient source flow, expansion-valve fault, or refrigerant leakage.",
        "Manual reset; block compressor; force immersion heater.",
        "Check source flow; replace compressor unit.",
    ),
    311: AlarmInfo(
        "High pressure switch off protection",
        "High-pressure switch opened three times within one hour.",
        "Insufficient water flow, compressor fault, or switch fault/poor connection.",
        "Manual reset; block compressor; force immersion heater.",
        "Check system flow; replace compressor unit.",
    ),
    312: AlarmInfo(
        "Excessive exhaust temperature protection",
        "High BT20 discharge temperature occurred three times within one hour.",
        "Compressor malfunction.",
        "Manual reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    313: AlarmInfo(
        "Driver IPM overtemperature protection",
        "High inverter-board temperature occurred six times within one hour.",
        "Compressor malfunction or internal inverter fault.",
        "Manual reset; block compressor; force immersion heater.",
        "Check power supply; replace compressor unit.",
    ),
    315: AlarmInfo(
        "Over-pressure protection of high pressure",
        "High BP2 pressure occurred three times within one hour.",
        "Insufficient water flow or compressor malfunction.",
        "Manual reset; block compressor; force immersion heater.",
        "Check system flow; replace compressor unit.",
    ),
    325: AlarmInfo(
        "Low-pressure protection for high-pressure",
        "Low pressure at BP2 occurred three times within one hour.",
        "Compressor envelope constraints.",
        "Manual reset; block compressor; force immersion heater.",
        "Check system flow, system/source temperature, source flow, and source temperature.",
    ),
    326: AlarmInfo(
        "High-pressure protection for low-pressure",
        "High pressure at BP1 occurred three times within one hour.",
        "Compressor envelope constraints.",
        "Manual reset; block compressor; force immersion heater.",
        "Check system flow, system/source temperature, source flow, and source temperature.",
    ),
    327: AlarmInfo(
        "Fault of water flow switch on the ground source side",
        "GP4/BF2 low flow occurred three times within one hour.",
        "Insufficient source-medium flow.",
        "Manual reset; block compressor; force immersion heater.",
        "Check source-medium flow.",
    ),
    333: AlarmInfo(
        "Com W2W Module 1 Error",
        "Communication with compressor module EP10 was lost.",
        "Wiring issue, inverter PCB fault, or broken main-board fuse.",
        "Manual reset; block compressor, force immersion heater, and DHW pump GP2.",
        "Check power supply and communication cable/connections between compressor unit and main board.",
    ),
    334: AlarmInfo(
        "Com W2W Module 2 Error",
        "Communication with compressor module EP11 was lost.",
        "Wiring issue, inverter PCB fault, or broken main-board fuse.",
        "Manual reset; block compressor, force immersion heater, and DHW pump GP2.",
        "Check power supply and communication cable/connections between compressor unit and main board.",
    ),
}
